spring:
  devtools:
    livereload:
      enabled: true
  application:
    name: booking
  datasource:
    url: jdbc:postgresql://db:5432/booking
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            "[non_contextual_creation]": true
    open-in-view: false
    show-sql: true